package comp3111.covid;

import java.io.File;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

import comp3111.covid.datastorage.Database;
import comp3111.covid.tabs.*;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Tab;
import javafx.scene.control.TabPane;
import javafx.scene.control.TextArea;
import javafx.scene.text.Text;

/**
 * Building on the sample skeleton for 'ui.fxml' Controller Class generated by SceneBuilder 
 */
public class Controller {

    
    @FXML private Button fileChoosingButton;
    @FXML private TextArea textAreaConsole; // the console that was gone
    
    // Tabs under the main Tab pane
    @FXML private Tab tabReport1;
    @FXML private Tab tabReport2;
    @FXML private Tab tabReport3;
    @FXML private Tab tabApp1;
    @FXML private Tab tabApp2;
    @FXML private Tab tabApp3;
    @FXML private Tab tabC3;
    
    // controller for all tabs
    @FXML private TabA1pageController tabA1pageController;
    @FXML private TabA2pageController tabA2pageController;
    @FXML private TabB1pageController tabB1pageController;
    @FXML private TabB2pageController tabB2pageController;
    @FXML private TabC1pageController tabC1pageController;
    @FXML private TabC2pageController tabC2pageController;
    @FXML private TabC3pageController tabC3pageController;
    
    @FXML private TabPane tabPane;
    
    @FXML private Text popUpMessageText;
    
    private Context context = Context.getInstance();
    private Database database = context.getDatabase();
    
    //launch the CSV file chooser
    private File chooseCSVFile() {
    	JFileChooser csvChooser = new JFileChooser("./src/main/resources/dataset");
    	FileNameExtensionFilter csvFilter = new FileNameExtensionFilter("CSV files", "csv");
    	csvChooser.setFileFilter(csvFilter);
    	int chooserReturnVal = csvChooser.showOpenDialog(null);
    	if(chooserReturnVal == JFileChooser.APPROVE_OPTION) {
    		return csvChooser.getSelectedFile();
    	}
    	return null;
    }
    
    @FXML
    //triggered by button
    void importCSVtoDatabase(ActionEvent event) {
    	File csvFile = chooseCSVFile(); // Official function
    	//File csvFile = new File("./src/main/resources/dataset/COVID_Dataset_v1.0.csv");

    	if(csvFile != null) {
    		this.database.importCSV(csvFile);
        	System.out.println("successfully imported");
        	this.database.printDatabaseContent();
        	
        	this.tabA1pageController.updateCheckboxList();
        	this.tabA2pageController.updateCheckboxList();
        	this.tabB1pageController.updateCheckboxList();
        	this.tabB2pageController.updateCheckboxList();
        	this.tabC1pageController.updateCheckboxList();
        	this.tabC2pageController.updateCheckboxList();
        	this.tabC3pageController.initAfterImport();
        	
        	this.tabReport1.setDisable(false);
        	this.tabReport2.setDisable(false);
        	this.tabReport3.setDisable(false);
        	this.tabApp1.setDisable(false);
        	this.tabApp2.setDisable(false);
        	this.tabApp3.setDisable(false);
        	this.tabC3.setDisable(false);
    	}
    }
}

